# Generated by Django 5.2.3 on 2025-06-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0017_alter_expense_expense_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='file',
            field=models.FileField(default='bills/default.pdf', upload_to='bills/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
